### ISSUE TITLE
Message in Brackets Developer Tools console

### ISSUE THREAD

**Issue by Mark-Simulacrum** [MiguelCastillo/Brackets-Ternific#36]
I'm not sure why, but I am seeing the following message after typing `console.`. This is a little annoying, especially when I'm logging things into the console as well.

Hopefully this is an easy fix!

```
====> error null text.js /home/mark/projects/Brackets-InteractiveLinter/
```

**Comment by MiguelCastillo** [comment]
This issue is taken care of
