### ISSUE TITLE
Installation via Extension Manager doesn't seem to work

### ISSUE THREAD

**Issue by herrernst** [MiguelCastillo/Brackets-Ternific#38]
I've just downloaded Brackets 1.1 and installed Ternific 0.7.1 with Brackets' Extension Manager. Unfortunately, I do not get any completions.
When I open Brackets' Developer Tools, I see ```file:///Users/user/Library/Application%20Support/Brackets/extensions/user/ternific/libs/tern/node_modules/acorn/acorn.js: Failed to load resource: net::ERR_FILE_NOT_FOUND```.
When I `cd` into `ternific/libs` and issue `npm install`, it works. Shouldn't this happen automatically or the modules be provided in the downloaded extensions-zip-file?

**Comment by hacker112** [comment]
I had the same problem. 
Herrernst: I guess you mean `cd ternific/libs/tern && npm install`. `tern` was missing from the path.

**Comment by herrernst** [comment]
Yes, @hacker112, exactly like you say, forgot to copy-paste `tern`.

**Comment by MiguelCastillo** [comment]
Thanks for reporting this folks.  I will take a look as soon as I can since it seems like this is going to affect pretty much everyone. :/

**Comment by MiguelCastillo** [comment]
Fixed https://github.com/MiguelCastillo/Brackets-Ternific/commit/587564d16838f4c7228fe8b1d51936e8f3eea4ac.

I just pushed a patch to the extension registry.  Thanks again folks :)
