### ISSUE TITLE
Tern defs not loaded?

### ISSUE THREAD

**Issue by hacker112** [MiguelCastillo/Brackets-Ternific#39]
The newest version does not seem to suggest keywords defined in tern/defs. 
Earlier i could write `fun` and it would suggest `function` for example.

**Comment by MiguelCastillo** [comment]
Hmmm, I just tried it out with the version from the registry and it worked.  Did you restart brackets after you updated to 0.7.2?

![screen shot 2015-01-22 at 10 48 10 am](https://cloud.githubusercontent.com/assets/1457701/5858852/4bf7a380-a224-11e4-824e-cdd04425bd80.png)

**Comment by hacker112** [comment]
I did probably not do that then, but I did it now. It did not improve.

![x](https://cloud.githubusercontent.com/assets/620746/5858995/6390bde6-a257-11e4-8167-563559847bb7.png)

It did not work in 0.7.1 either. I am running Mac OS X 10.9.5. It worked when I used 0.6.1.
Any ideas?

**Comment by MiguelCastillo** [comment]
Are there any console errors?  Can you enable logging in ternific to check if there are any errors being reported?


You can enable logging by bringing up the developer tools, and in the console run `ternificLogger.enableAll()`.  You should start seeing ternific logs.

Can you also verify if you have ternific/libs/tern/defs/reseved.json`?  You would find that in the brackets extension's directory.

I really appreciate your help.

**Comment by MiguelCastillo** [comment]
You are right, https://github.com/MiguelCastillo/Brackets-Ternific/blob/master/libs/tern/.tern-project overrides this https://github.com/MiguelCastillo/Brackets-Ternific/blob/master/.tern-project.

I changed it so that https://github.com/MiguelCastillo/Brackets-Ternific/blob/master/.tern-project is default settings, which will have `reserved.json`.

Will push that out shortly.  Thanks for your help!!

**Comment by MiguelCastillo** [comment]
The fix is pushed to mater.  Do you think you can install ternific from the master branch and give it another quick test?  It seems like you are finding these issues that I should be finding :)

**Comment by hacker112** [comment]
Works like a charm :-) Thanks!

**Comment by MiguelCastillo** [comment]
Thank you!

fixed with https://github.com/MiguelCastillo/Brackets-Ternific/commit/46b12cf6c9f7f85319639e904e285f56ed1f58a6
