### ISSUE TITLE
AngularJS support

### ISSUE THREAD

**Issue by trazek** [MiguelCastillo/Brackets-Ternific#40]
Does this plugin support custom objects/services/factories for AngularJS? Is there an example .tern-project file available including Angular? I would love to use this with my Brackets setup.

**Comment by abdelouahabb** [comment]
I got this : 
![sans titre](https://cloud.githubusercontent.com/assets/2527234/10834382/4da407f8-7e99-11e5-9a6c-977009eb0b88.png)

Make a blank file inside the root of your project, name it `.tern-project` and put:

    {
      "libs": [
        ""
      ],
      "loadEagerly": [ "js/*.js"],
      "plugins": {
        "angular": {}
      }
    }


you dont need `angular` because it contains one in the directory `C:\Users\`YourName\AppData\Roaming\Brackets\extensions\user\ternific\node_modules\tern\plugin`

**Comment by MiguelCastillo** [comment]
@abdelouahabb Thanks for responding. This one definitely fell through the cracks.  Your configuration seems correct to me.

@trazek Please let us know if what @abdelouahabb provided resolves your issue.

**Comment by abdelouahabb** [comment]
@MiguelCastillo any idea how to include `React` because it seems that a special version of the library must be made, putting the lib in the folder was invisible to be loaded :(

**Comment by MiguelCastillo** [comment]
Yeah, you should be able to specify absolute/relative paths to it.  Here is an example of a config file that loads a react plugin that is in ternific's "custom" directory. Relative paths are relative to ternific's install directory...

```
{
  "plugins": {
    "./custom/react": {}
  }
}
```

You can specify an absolute path to the plugin file as well.  Perhaps I can add a way to specify a way to load a file relative to the project, but that does not yet exist.

**Comment by MiguelCastillo** [comment]
BTW, this is the method loads the plugins in the worker thread.  https://github.com/MiguelCastillo/Brackets-Ternific/blob/master/TernWorker.js#L43

**Comment by abdelouahabb** [comment]
@MiguelCastillo dident load it, I created a new directory, and put `react` there `C:\Users\Abdelouahab\AppData\Roaming\Brackets\extensions\user\ternific\node_modules\tern\custom`

    {
      "libs": [
        ""
      ],
      "loadEagerly": [ "js/*.js"],
      "plugins": {
        "./custom/react": {}
      }
    }

**Comment by MiguelCastillo** [comment]
Yeah it wont find because you are putting it in tern's directory.  The path is relative to ternific.  You can probably confirm this if you opened up the debug console :)

You can either put "custom/react.js" directly under ternific or change your config to 

```
{
  "libs": [
    ""
  ],
  "loadEagerly": [ "js/*.js"],
  "plugins": {
    "./node_modules/tern/custom/react": {}
  }
}
```

**Comment by abdelouahabb** [comment]
Says that this file is missing? (an empty file?)
![sans titre](https://cloud.githubusercontent.com/assets/2527234/10848940/bff53158-7f1e-11e5-9d15-998532b1b347.png)

**Comment by MiguelCastillo** [comment]
Yeah, that error is different.  That one is because you have an empty entry in the `libs` section. I should add a guard in the code for that, even though that's pretty much handling issues with an invalid config file, so I am not sure how I feel silently handling it yet.

**Comment by abdelouahabb** [comment]
Now I dont get any error, but still not autocompletion detected :(

**Comment by MiguelCastillo** [comment]
To be honest, I have not used the react plugin. So I couldn't really tell you what to expect...  Would you mind posting a link for it so that I can take a look?

**Comment by abdelouahabb** [comment]
This is the defacto of the DOM manipulation now :D 
here is what it gives in PyCharm
![sans titre](https://cloud.githubusercontent.com/assets/2527234/10850916/6edaca76-7f28-11e5-9afa-55e8805fd4d7.png)

**Comment by MiguelCastillo** [comment]
Ah! defacto you say! @abdelouahabb I love the spirit. :)   I meant specifically if you knew of a tern plugin for react that you were using.  Not about react itself :)

**Comment by abdelouahabb** [comment]
looool sorry, I searched on internet, and found that there is a plugin but have limitation https://github.com/angelozerr/tern-react

**Comment by MiguelCastillo** [comment]
Cool, that's what I wanted to know.  Which react plugin for tern are you using.  Is that the one you are using?  Or were you expecting it to be a built in plugin?

BTW, I love react. Use it and abuse it everyday :)

**Comment by abdelouahabb** [comment]
React is awesome :dancer: 
but the problem is that to use it, there are two main solutions which are : 
Commercial using JetBrain products, or, Atom which is memory-hungry.
and in Brackets, I thought it will be loaded automatically, so, it needs another plugin?
NB: I come from python world, and I thought it will be the same concept of loading methods without requiring independant plugin for every library.

**Comment by MiguelCastillo** [comment]
I hear ya.  So, first off... Tern does not yet ship with react... :-/  I am hoping this will change somewhat soon.

Second, I would love to see support for react in tern either way... So do you think you can try to get that tern plugin working?  I am going to try that on my side later this evening as well.  But it would be really helpful if you can independently get it working :)

**Comment by abdelouahabb** [comment]
installed it at `C:\Users\Abdelouahab\AppData\Roaming\Brackets\extensions\user\ternific\node_modules\tern-react` and still nothing

**Comment by MiguelCastillo** [comment]
cool, thanks for trying. I will give it a shot tonight and let you know.

**Comment by abdelouahabb** [comment]
thank you, and sorry for delay :D
