### ISSUE TITLE
Not getting all Meteor code hints

### ISSUE THREAD

**Issue by jeffshaver** [MiguelCastillo/Brackets-Ternific#42]
Downloaded tern-meteor (the meteor.js file) from here: https://github.com/Slava/tern-meteor

Put the meteor.js file into the ternific directory in Library/Application Support/Brackets/extensions/user/ternific

Then did both of these at separate times:

Changed the default .tern-project to be include "meteor": {} in the plugins section

Created a project-specific .tern-project and included "meteor": {} in the plugins section

I get code hints for Meteor and a few others, but not for Template or Mongo or several others.

.tern-project: 
```
{
  "libs": [
    "reserved",
    "browser",
    "chai",
    "ecma5",
    "jquery",
    "lodash"
  ],
  "loadEagerly": ["*.js", "*/*.js", "*/*/*.js", "*/*/*/*.js"],
  "async": true,
  "dontLoad": [".meteor"],
  "plugins": {
    "requirejs": {},
    "doc_comment": {},
    "component": {},
    "meteor": {}
  }
}
```

**Comment by MiguelCastillo** [comment]
Thank you for logging this issue.  I just tested this with the very latest from [here](https://github.com/Slava/tern-meteor/blob/master/meteor.js) and I get hints for Template and Mongo.

I think the issue might be that you could be copying the meteor plugin to wrong place.  Try putting it in ternific/libs/tern/plugin.  There should already be one there, so you can just replace that.

**Comment by jeffshaver** [comment]
@MiguelCastillo You are 100% correct. I did not realize that it had to go into libs/tern/plugin/

**Comment by MiguelCastillo** [comment]
Very cool, glad it worked.  I just updated the meteor plugin so that next ternific update already has the latest for ya.

-mc

**Comment by yochrepi** [comment]
**Windows users on the Release 1.4 build 1.4.0-16380 (release 273804eb3)**
Put the meteor.js file in the `C:\Users\UserName\AppData\Roaming\Brackets\extensions\user\ternific\node_modules\tern\plugin` folder
