### ISSUE TITLE
Isn't reading from other files

### ISSUE THREAD

**Issue by ThaisRobba** [MiguelCastillo/Brackets-Ternific#43]
1. Create two different js files
2. Create one function in the first file
3. Type in the name of the function on the second file
4. Doesn't show up on Ternific :cry: 

On my notebook, it did show up once when I had both files open with modifications and unsaved but on my desktop, it just won't show.

Regular Brackets hints finds the function name correctly.

**Comment by MiguelCastillo** [comment]
@OttoRobba are these two javascript file using `require` statements to find each other?  If it is not too much trouble and the files are small, do you think you can paste them here?

**Comment by OttoRobba** [comment]
They don't use require  and yes they are really tiny files. I was specifically testing Ternific for teaching.

First file:

    //test.js
    /**
     * Draws a shape and all.
     * @param {String} type    what to draw
     * @param {Object} options How to draw it   
     */
    var drawShape = function(type, options) {
      console.log(type);
     };

And the second file:

    //test2.js
    /**
     * Also Draws a shape and all.
     * @param {String} type    what to draw
     * @param {Object} options How to draw it   
     */
    var drawShape2 = function(type, options) {
      console.log(type);
     };

If I start typing 'draw' on test.js, it will only show completion for drawShape and vice-versa. If I make a third file, it will not show completion for any of the drawShape functions.
