### ISSUE TITLE
Error reporting error

### ISSUE THREAD

**Issue by HookyQR** [MiguelCastillo/Brackets-Ternific#68]
fileReader error sends a string and error reporter expects and Error object. Can be solved by changing line 30 of fileReader.js to:
```javascript
err = err ? err : new Error(exists ? "Unknown file error" : filePath + " was not found");
```

**Comment by MiguelCastillo** [comment]
fixed https://github.com/MiguelCastillo/Brackets-Ternific/pull/73.

Thanks for looking into this!
