### ISSUE TITLE
basic javascript suggestion not appearing

### ISSUE THREAD

**Issue by danielo515** [MiguelCastillo/Brackets-Ternific#76]
Hello,

I expected this plugin to provide some basic javascript auto completion. Things like `[ ].m` does not get any auto completion.

Is there anything that I have to do to enable this?

Regards

**Comment by MiguelCastillo** [comment]
Yup, I expect basic stuff to function just fine.  Do you mind sharing with me in a gist or pasted in here a sample code I can use to test this behavior?

**Comment by danielo515** [comment]
Hello again,

It is now working. Something bad were happening before. I'll keep an eye open, maybe it was a matter of scope.

Sorry for asking this here, but, is there any way to make the plugin "scan" certain folders for functions ?

**Comment by MiguelCastillo** [comment]
@danielo515 will close this one.  let's open a new bug if the issue comes back.  Also, there really isn't a way to scan folders for functions.  What are you looking to do?
