### ISSUE TITLE
Does Ternific provide code completion for other source files in my project?

### ISSUE THREAD

**Issue by Rolias** [MiguelCastillo/Brackets-Ternific#89]
I've read the docs here and looked at Tern and even seen [this demo](http://ternjs.net/doc/demo/#ES6) which makes me think that inside Brackets I should see code completion for other modules I have written but I can't seem to get it to work. I tried adding the following line to the .tern-project file at the root of my project 
`  "loadEagerly": ["*.js", "*/*.js", "*/*/*.js", "*/*/*/*.js"],`
In case it wasn't loading my files. 
I am working with Brackets on a Mac using node.js. I created an acTest.js file in the same folder as utils.js and I wrote
```
var util = require ("./utils");
util.log("Hello");
```
I got no drop down after typing `util.` I get no drop down if I hit ctrl-space. 
I can run the file in node and it puts out the message as expected. 
I've disabled all other extensions except for Delkos Dark Theme and Monokai Dark Soda theme which won't disable for some reason. I do see basic drop down help for libraries. For example typing `Math.` shows the expected drop down list. 
Am I missing something in the .tern-project file or does this extension only support code assist for known libraries?

**Comment by Rolias** [comment]
Being new to all this I though ternific was needed to get autocompletion at all. I just disabled ternific and the auto completion for libraries AND for my files now works. While I'll miss the Ctrl-R quick rename I need auto-completion much more. Not at all sure why Ternific would disable the default tern editor support.

**Comment by MiguelCastillo** [comment]
Hi @Rolias - sorry for my delayed response.  You really don't need ternific to get JS hints.  I created ternific because I have tuned the sorting algorithm to my liking amongst other features.

Curious.  Did you just open a whole directory and files in it wouldn't show hints or did you just open the one file without a "project"?  A "project" is basically any directory that Brackets can use as the working directory.

**Comment by Rolias** [comment]
I had the entire project folder opened. It's a node project so that
includes many things (like node_modules) even though my actual code base is
only a dozen files or so. At any one time I usually have 12 or fewer files
in the working lists. Didn't seem to matter though when I only had two
files open it still wouldn't give hints. It is better now but I had to give
up on your oh so useful ctrl-r rename refactoring.

Thanks for responding.
